# Generated by Django 6.0.3 on 2026-04-04 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.IntegerField(default=60)),
            ],
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('match', 'Matching'), ('ynng', 'Yes / No / Not Given'), ('headings', 'Match Headings'), ('matching_info', 'Matching Information')], default='mcq', max_length=20),
        ),
        migrations.CreateModel(
            name='ReadingExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.readingexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ielts.readingexam')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.readingpassage')),
            ],
            options={
                'ordering': ['exam', 'order'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'order'), name='unique_exam_section_order')],
            },
        ),
    ]
