# Generated by Django 6.0.3 on 2026-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_chocolates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolates',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
